// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/[name].tsx";
import * as $1 from "./routes/api/joke.ts";
import * as $2 from "./routes/index.tsx";
import * as $$0 from "./islands/AboutSection.tsx";
import * as $$1 from "./islands/ContactList.tsx";
import * as $$2 from "./islands/Counter.tsx";
import * as $$3 from "./islands/ProjectList.tsx";

const manifest = {
  routes: {
    "./routes/[name].tsx": $0,
    "./routes/api/joke.ts": $1,
    "./routes/index.tsx": $2,
  },
  islands: {
    "./islands/AboutSection.tsx": $$0,
    "./islands/ContactList.tsx": $$1,
    "./islands/Counter.tsx": $$2,
    "./islands/ProjectList.tsx": $$3,
  },
  baseUrl: import.meta.url,
};

export default manifest;
