// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/index.tsx";
import * as $1 from "./routes/jons-tuner.tsx";
import * as $2 from "./routes/privacy.tsx";
import * as $$0 from "./islands/ThreeBackground.tsx";
import * as $$1 from "./islands/ThreeOrsiGlitch.tsx";

const manifest = {
  routes: {
    "./routes/index.tsx": $0,
    "./routes/jons-tuner.tsx": $1,
    "./routes/privacy.tsx": $2,
  },
  islands: {
    "./islands/ThreeBackground.tsx": $$0,
    "./islands/ThreeOrsiGlitch.tsx": $$1,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
