# name: Build & deploy

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - name: Configure AWS credentials
#         uses: aws-actions/configure-aws-credentials@v1
#         with: 
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: us-east-2
#       - name: Use Deno 1.x
#         uses: denoland/setup-deno@v1
#         with:
#           deno-version: v1.x
#       - name: Install AlephJs
#         run: deno run -A https://deno.land/x/aleph/install.ts
#       - name: Build
#         run: aleph build
#       - name: Deploy
#         run: aws s3 sync ./dist s3://orsi.dev
